# Generated by Django 3.0.7 on 2020-12-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_language_settinglang'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='lang',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('fa', 'دری')], max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='settinglang',
            name='lang',
            field=models.CharField(choices=[('en', 'English'), ('fa', 'دری')], default='', max_length=8),
            preserve_default=False,
        ),
    ]
