# Generated by Django 3.0.7 on 2020-12-16 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0006_increase_name_max_length'),
        ('user', '0003_profile_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='currencies.Currency'),
        ),
    ]
